github-organization: "spring-gradle-plugins"
github-repository: "dependency-management-plugin"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
milestone: "1.0.x"
build-name: "dependency-management-plugin"
concourse-url: "https://ci.spring.io"
task-timeout: 1h00m
